function graphdraw(A,xy,pointsize)
   n = length(A);
   
   red = ones(n,1)*[1 0 0];

   GraphPlot(xy,A,            ...
          'randedges', 0,           ...
          'nodecolors', red,    ...
          'Scores', [1:n]', ...
          'edgewidth',2,           ...
          'alpha', 1,               ...
          'pointsize',  pointsize);  
end
